Import('base_env')

src_files = Glob('src/*.cpp')

base_env.Program('npserver',
                 src_files,
                 LIBS=['npcommon', 'pthread', 'boost_thread', 'boost_log'],
                 LIBPATH=['#common'])
